[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["clean"]

[tasks.dump]
command = "sh"
args = ["./scripts/signals/dl_dump.sh"]

[tasks.generate]
command = "lua"
args = ["./scripts/signals/main.lua"]

[tasks.debug]
env = { "RUST_LOG" = "lib" }
command = "cargo"
args = ["run", "--", "./test/program.ffc"]

[tasks.flow]
dependencies = ["format", "generate", "build", "test"]
